### ISSUE TITLE
Issue With Jellyfin URL

### ISSUE THREAD

**Issue by AidanHilt** [buildarr/buildarr-jellyseerr#33]
Hi! I'm trying to set up Buildarr to automatically initialize Jellyseerr, and I'm running into an issue. When I try to add the Jellyfin authentication, Buildarr reports this error:
```
buildarr_jellyseerr.exceptions.JellyseerrAPIError: Unexpected response with status code 404 from from 'POST http://jellyseerr:80/api/v1/auth/jellyfin': INVALID_URL
```

The logs for Jellyseerr have the following entry: 
```
2024-06-20T05:49:38.369Z [debug][Jellyfin API]: Failed to authenticate with headers: Request failed with status code 404 {"ip":"192.168.0.95"} 
2024-06-20T05:49:38.390Z [error][Auth]: The provided Jellyfin is invalid or the server is not reachable. {"error":"INVALID_URL","status":404,"hostname":"http://jellyfin:80/emby:undefinedundefined"}
```

This is my Jellyfin configuration block in buildarr.yml:
```
        jellyfin:
          server_url: "jellyfin:80/emby"
          username: "admin"
          password: "-------------"
          email_address: someone@somewhere.com
          external_url: null
          libraries:
          - Movies
```

All of these are running in Docker containers in a local Kubernetes cluster. It looks to me like something is attempting to "turn" the server_url field into a URL, since it's adding the 'http://' protocol. If you don't have time to look into this, do you have any idea where this might be happening?
